version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specify Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the application..."
      - npm run build || echo "No build step required"  # Runs build if needed, otherwise skips

  post_build:
    commands:
      - echo "Running tests..."
      - npm test || echo "No tests found, skipping tests"  # Runs tests if available
      - echo "Build and tests completed on $(date)"

artifacts:
  files:
    - '**/*'  # Includes all files
  base-directory: .  # Ensures all necessary files are included
  discard-paths: no  # Keeps the file structure intact

cache:
  paths:
    - node_modules/**  # Cache dependencies for faster builds
