version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specify Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the application..."
<<<<<<< HEAD
      - npm run build  # Only needed if using TypeScript or Babel
=======
      - npm run build || echo "No build step required"  # Runs build if needed, otherwise skips
>>>>>>> a4f6942 (Update again)

  post_build:
    commands:
      - echo "Running tests..."
<<<<<<< HEAD
      - npm test  # Run tests to validate the build
=======
      - npm test || echo "No tests found, skipping tests"  # Runs tests if available
>>>>>>> a4f6942 (Update again)
      - echo "Build and tests completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: .  # Includes everything
<<<<<<< HEAD
  discard-paths: no

cache:
  paths:
    - node_modules/**  # Cache dependencies
=======
  discard-paths: no  # Keeps file structure intact

cache:
  paths:
    - node_modules/**  # Cache dependencies for faster builds
>>>>>>> a4f6942 (Update again)
